config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos
  resources :users



  get "/", to: "home#index"
  #post "users/login", to: "users#login"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
end

app/models/Todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  #has table user
  #todo table will contain user id.
  validates :todo_text, presence: true
  validates :due_date, presence: true

  def to_displayable_string
    display_status = completed ? "[X]" : "[ ]"
    display_date = due_today? ? nil : due_date
    "#{id}.  #{display_status} #{todo_text} #{display_date}"
  end

  def self.due_today
    all.where("due_date = ?", Date.today)
  end

  def self.over_due
    where("due_date < ? and (not completed)", Date.today)
  end

  def due_today?
    due_date == Date.today
  end

  def self.due_later
    all.where("due_date > ?", Date.today)
  end

  def self.completed
    all.where(completed: true)
  end

  def self.not_completed
    all.where(completed: false)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :todos

  validates :first_name, presence: true
  validates :email, presence: true

  def to_displayable_string
    "name:#{name} gmail:#{gmail} password#{password}"
  end

  def self.new_user(newuser)
    first_name = newuser[:first_name]
    last_name = newuser[:last_name]
    email = newuser[:email]
    password = newuser[:password_digest]
    new(first_name: first_name, last_name: last_name, email: email, password: password)
  end
  def self.check(credentials)
    where("gmail=? and password=?", credentials["email"], credentials["password"]).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    if @current_user
      return @current_user
    end
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render :index
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password_digest])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your login attempt is invalid"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
# todos_controller.rb
class TodosController < ApplicationController

  def index
    #render plain: Todo.all.order(:due_date).map { |todo| todo.to_pleasant_string }.join("\n")
    @todos = current_user.todos
    render :index
  end

  def show
    id = params[:id]
    todo = current_user.todos.find(id)
    render plain: Todo.find(id).to_pleasant_string
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(",")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = Todo.update(id, completed: completed)
    #render plain: "Updated todo completed status to #{completed}"
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.find(id)
    todo.destroy
    redirect_to todos_path
  end

  def all
    render #all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render plain: User.all.map { |user| user.to_displayable_string }.join("\n")
  end

  def new
    # render "users/new"
  end

  def create
    user = User.new_user(params)
    if user.save
      session[:current_user_id] = user.id
      flash[:success] = "Signed up sucessfully! You are logged in automatically"
      redirect_to ""
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def check
    render plain: User.check(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
  <div class="header">
    <p class="logo">Caffeteria Management</p>
    <div class="header-right">
      <p class="nav-text"><%= link_to "Signup", new_user_path,{:style=>'color:#FFFFFF;', :class => "css_class"}%></p>
      <p class="nav-text"><%= link_to "Signin", new_sessions_path ,{:style=>'color:#FFFFFF;', :class => "css_class"} %></p>
      <p class="nav-text"><%= link_to "Signout", new_sessions_path ,{:style=>'color:#FFFFFF;', :class => "css_class"} %></p>
    </div>
  </div>


  <div class="topnav">
  <a href="#">Link</a>
  <a href="#">Link</a>
  <a href="#">Link</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caffeteria Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%if @current_user%>
      <p class = UserHeader>
        Hello
        <%= @current_user.first_name %>
        <%= link_to "sign-out",destroy_session_path,method: "delete"%>
      </p>

       <div class="header">
    <p class="logo">Caffeteria Management</p>
    <div class="header-right">
      <p class="nav-text"><%= link_to "Signup", new_user_path,{:style=>'color:#FFFFFF;', :class => "css_class"}%></p>
      <p class="nav-text"><%= link_to "Signin", new_sessions_path ,{:style=>'color:#FFFFFF;', :class => "css_class"} %></p>
       <%= link_to "sign-out",destroy_session_path,method: "delete"%> </div>
  </div>
    <% end %>

    <% if flash[:error] %>
      <div class="Flash-error">
        <%= flash[:error] %>
      </div>
    <% end %>

    <% if flash[:success] %>
      <p class=Flash-success>
        <%= flash[:success] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="Section">
  <div class="SectionTitle">
    <p class="SectionTitle-text"><%= section_title %></p>
    <p class="SectionTitleCount"><%= todos.completed.count %>/<%= todos.count %></p>
  </div>
  <ul>
    <% todos.each do |todo| %>
      <li class='MyTodoItem'>
        <div class='MyTodoItem-Container'>

          <%= form_with(url:"/todos/#{todo.id}", method: "put") do %>
            <%= check_box_tag(name="completed",value = "1",checked = todo.completed,options = {onclick: "this.form.submit()"}) %>
          <% end %>

          <% class_name = todo.completed ? "MyTodoItem-text-completed" : "MyTodoItem-text" %>
          <p class=<%= class_name %>> <%= todo.todo_text %> </p>

          <% if show_due_date %>
            <p class='MyTodoItem-dueDate'><%= todo.due_date.to_s(:short) %></p>
          <% end %>

          <a class="MyTodoItem-delete" href="javascript:void(0)">
            <%= form_with(url: "/todos/#{todo.id}", method:"delete") do %>
              <%= image_submit_tag("trash.png") %>
            <% end %>
          </a>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
 <div class="header">
    <p class="logo">Caffeteria Management</p>
    <div class="header-right">
      <p class="nav-text"><%= link_to "Signup", new_user_path,{:style=>'color:#FFFFFF;', :class => "css_class"}%></p>
      <p class="nav-text"><%= link_to "Signin", new_sessions_path ,{:style=>'color:#FFFFFF;', :class => "css_class"} %></p>
      <p class="nav-text"><%= link_to "Signout", new_sessions_path ,{:style=>'color:#FFFFFF;', :class => "css_class"} %></p>
    </div>
  </div>

<main class="MyTodoMain">
  <article>
    <h1 class="MyTodo-title">My To-do List</h1>
    <%= form_with(url: "/todos", method:"post", class: "MyTodo") do %>
      <%= text_field_tag 'todo_text', nil, placeholder: 'What\'s next?' , class: "MyTodo-text" %>
      <%= date_field_tag 'due_date' , class:"MyTodo-date" %>
      <%= submit_tag "Add" , class: "MyTodo-button" %>
    <% end %>

    <%= render partial:"todo-section", locals:{
        section_title:"Overdue",
        todos: @todos.over_due,
        show_due_date: true
      } %>
    <%= render partial:"todo-section", locals:{
        section_title:"Due Today",
        todos: @todos.due_today,
        show_due_date: false
      } %>
    <%= render partial:"todo-section", locals:{
        section_title:"Due Later",
        todos: @todos.due_later,
        show_due_date: true
      } %>
  </article>
</main>

app/views/users/new.html.erb
<div class="layer">
  <div class="signup-form">
    <h1>Sign up</h1>
    <section class="NewUser">
      <%= form_with url: users_path do |form| %>
      <%= form.text_field :first_name,class: "Form-input",placeholder: "name",autofocus: "autofocus" %>
      <%= form.email_field :email,placeholder: "email",class: "Form-input" %>
      <%= form.password_field :password_digest,placeholder: "password",class: "Form-input" %>
      <%= form.submit "Sign Up!",class: "signup-btn" %>
      <% end %>
    </section>
  </div>
  </div>